// Code generated by the Lingua Franca compiler from:
// file://home/foobar/final/lingua_franca/src/bluetooth_module_rename.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/final/lingua_franca/src-gen/bluetooth_module_rename"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_robotble.h"
#include "_display.h"
#include "_bluetooth_module_rename_main.h"
typedef enum {
    bluetooth_module_rename_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[bluetooth_module_rename_main],bluetooth_module_rename_main,_lf_number_of_workers,2,3,0,0,5,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _bluetooth_module_rename_main_main_self_t* bluetooth_module_rename_main_self[1];
    SUPPRESS_UNUSED_WARNING(bluetooth_module_rename_main_self);
    _robotble_self_t* bluetooth_module_rename_ble_self[1];
    SUPPRESS_UNUSED_WARNING(bluetooth_module_rename_ble_self);
    _display_self_t* bluetooth_module_rename_disp_self[1];
    SUPPRESS_UNUSED_WARNING(bluetooth_module_rename_disp_self);
    // ***** Start initializing bluetooth_module_rename of class bluetooth_module_rename
    bluetooth_module_rename_main_self[0] = new__bluetooth_module_rename_main();
    bluetooth_module_rename_main_self[0]->base.environment = &envs[bluetooth_module_rename_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[bluetooth_module_rename_main].startup_reactions[startup_reaction_count[bluetooth_module_rename_main]++] = &bluetooth_module_rename_main_self[0]->_lf__reaction_0;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static char _initial[] = "AT+NAME?\r\n";
        bluetooth_module_rename_main_self[0]->name = _initial;
    } // End scoping.
    { // For scoping
        static int _initial = 0;
        bluetooth_module_rename_main_self[0]->count = _initial;
    } // End scoping.
    // Initiaizing timer bluetooth_module_rename.r.
    bluetooth_module_rename_main_self[0]->_lf__r.offset = 0;
    bluetooth_module_rename_main_self[0]->_lf__r.period = MSEC(10);
    // Associate timer with the environment of its parent
    envs[bluetooth_module_rename_main].timer_triggers[timer_triggers_count[bluetooth_module_rename_main]++] = &bluetooth_module_rename_main_self[0]->_lf__r;
    bluetooth_module_rename_main_self[0]->_lf__r.mode = NULL;
    // Initiaizing timer bluetooth_module_rename.t.
    bluetooth_module_rename_main_self[0]->_lf__t.offset = SEC(5);
    bluetooth_module_rename_main_self[0]->_lf__t.period = MSEC(100);
    // Associate timer with the environment of its parent
    envs[bluetooth_module_rename_main].timer_triggers[timer_triggers_count[bluetooth_module_rename_main]++] = &bluetooth_module_rename_main_self[0]->_lf__t;
    bluetooth_module_rename_main_self[0]->_lf__t.mode = NULL;
    
    bluetooth_module_rename_main_self[0]->_lf__reaction_0.deadline = NEVER;
    bluetooth_module_rename_main_self[0]->_lf__reaction_1.deadline = NEVER;
    bluetooth_module_rename_main_self[0]->_lf__reaction_2.deadline = NEVER;
    bluetooth_module_rename_main_self[0]->_lf__reaction_3.deadline = NEVER;
    {
        // ***** Start initializing bluetooth_module_rename.ble of class RobotBLE
        bluetooth_module_rename_ble_self[0] = new__robotble();
        bluetooth_module_rename_ble_self[0]->base.environment = &envs[bluetooth_module_rename_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_ble_self[0]->_lf_rx_char_width = -2;
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_ble_self[0]->_lf_check_uart_width = -2;
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_ble_self[0]->_lf_tx_char_width = -2;
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_ble_self[0]->_lf_tx_string_width = -2;
        envs[bluetooth_module_rename_main].startup_reactions[startup_reaction_count[bluetooth_module_rename_main]++] = &bluetooth_module_rename_ble_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        bluetooth_module_rename_ble_self[0]->_lf__reaction_0.deadline = NEVER;
        bluetooth_module_rename_ble_self[0]->_lf__reaction_1.deadline = NEVER;
        bluetooth_module_rename_ble_self[0]->_lf__reaction_2.deadline = NEVER;
        bluetooth_module_rename_ble_self[0]->_lf__reaction_3.deadline = NEVER;
        //***** End initializing bluetooth_module_rename.ble
    }
    {
        // ***** Start initializing bluetooth_module_rename.disp of class Display
        bluetooth_module_rename_disp_self[0] = new__display();
        bluetooth_module_rename_disp_self[0]->base.environment = &envs[bluetooth_module_rename_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        bluetooth_module_rename_disp_self[0]->_lf_line3_width = -2;
        envs[bluetooth_module_rename_main].startup_reactions[startup_reaction_count[bluetooth_module_rename_main]++] = &bluetooth_module_rename_disp_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        bluetooth_module_rename_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        bluetooth_module_rename_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing bluetooth_module_rename.disp
    }
    //***** End initializing bluetooth_module_rename
    // **** Start deferred initialize for bluetooth_module_rename
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of bluetooth_module_rename.
        bluetooth_module_rename_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of bluetooth_module_rename
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of bluetooth_module_rename.
        bluetooth_module_rename_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bluetooth_module_rename_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        bluetooth_module_rename_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        bluetooth_module_rename_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bluetooth_module_rename_main_self[0]->_lf__reaction_1.output_produced[count++] = &bluetooth_module_rename_main_self[0]->_lf_ble.check_uart.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of bluetooth_module_rename
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of bluetooth_module_rename.
        bluetooth_module_rename_main_self[0]->_lf__reaction_2.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bluetooth_module_rename_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        bluetooth_module_rename_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        bluetooth_module_rename_main_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bluetooth_module_rename_main_self[0]->_lf__reaction_2.output_produced[count++] = &bluetooth_module_rename_main_self[0]->_lf_ble.tx_string.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                bluetooth_module_rename_main_self[0]->_lf__reaction_2.output_produced[count++] = &bluetooth_module_rename_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of bluetooth_module_rename
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of bluetooth_module_rename.
        bluetooth_module_rename_main_self[0]->_lf__reaction_3.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bluetooth_module_rename_main_self[0]->_lf__reaction_3.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        bluetooth_module_rename_main_self[0]->_lf__reaction_3.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        bluetooth_module_rename_main_self[0]->_lf__reaction_3.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &bluetooth_module_rename_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bluetooth_module_rename_main_self[0]->_lf__reaction_3.output_produced[count++] = &bluetooth_module_rename_main_self[0]->_lf_disp.line0.is_present;
            }
        }
        
        // ** End initialization for reaction 3 of bluetooth_module_rename
    
        // **** Start deferred initialize for bluetooth_module_rename.ble
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of bluetooth_module_rename.ble.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of bluetooth_module_rename.ble
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of bluetooth_module_rename.ble.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &bluetooth_module_rename_ble_self[0]->base.allocations);
            bluetooth_module_rename_ble_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &bluetooth_module_rename_ble_self[0]->base.allocations);
            bluetooth_module_rename_ble_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &bluetooth_module_rename_ble_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    bluetooth_module_rename_ble_self[0]->_lf__reaction_1.output_produced[count++] = &bluetooth_module_rename_ble_self[0]->_lf_rx_char.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of bluetooth_module_rename.ble
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of bluetooth_module_rename.ble.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_2.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 2 of bluetooth_module_rename.ble
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of bluetooth_module_rename.ble.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_3.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 3 of bluetooth_module_rename.ble
        
        }
        // **** End of deferred initialize for bluetooth_module_rename.ble
        // **** Start deferred initialize for bluetooth_module_rename.disp
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of bluetooth_module_rename.disp.
            bluetooth_module_rename_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of bluetooth_module_rename.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of bluetooth_module_rename.disp.
            bluetooth_module_rename_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of bluetooth_module_rename.disp
        
        }
        // **** End of deferred initialize for bluetooth_module_rename.disp
    }
    // **** End of deferred initialize for bluetooth_module_rename
    // **** Start non-nested deferred initialize for bluetooth_module_rename
    // Set number of destination reactors for port ble.check_uart.
    // Iterate over range bluetooth_module_rename.ble.check_uart(0,1)->[bluetooth_module_rename.ble.check_uart(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bluetooth_module_rename_main_self[src_runtime]->_lf_ble.check_uart._base.num_destinations = 1;
        bluetooth_module_rename_main_self[src_runtime]->_lf_ble.check_uart._base.source_reactor = (self_base_t*)bluetooth_module_rename_main_self[src_runtime];
    }
    // Set number of destination reactors for port ble.tx_string.
    // Iterate over range bluetooth_module_rename.ble.tx_string(0,1)->[bluetooth_module_rename.ble.tx_string(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bluetooth_module_rename_main_self[src_runtime]->_lf_ble.tx_string._base.num_destinations = 1;
        bluetooth_module_rename_main_self[src_runtime]->_lf_ble.tx_string._base.source_reactor = (self_base_t*)bluetooth_module_rename_main_self[src_runtime];
    }
    // Set number of destination reactors for port disp.line1.
    // Iterate over range bluetooth_module_rename.disp.line1(0,1)->[bluetooth_module_rename.disp.line1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bluetooth_module_rename_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
        bluetooth_module_rename_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)bluetooth_module_rename_main_self[src_runtime];
    }
    // Set number of destination reactors for port disp.line0.
    // Iterate over range bluetooth_module_rename.disp.line0(0,1)->[bluetooth_module_rename.disp.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bluetooth_module_rename_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
        bluetooth_module_rename_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)bluetooth_module_rename_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range bluetooth_module_rename.ble.check_uart(0,1)->[bluetooth_module_rename.ble.check_uart(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of bluetooth_module_rename triggers 1 downstream reactions
            // through port bluetooth_module_rename.ble.check_uart.
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of bluetooth_module_rename, allocate an
            // array of trigger pointers for downstream reactions through port bluetooth_module_rename.ble.check_uart
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bluetooth_module_rename_main_self[src_runtime]->base.allocations); 
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges bluetooth_module_rename.ble.check_uart(0,1)->[bluetooth_module_rename.ble.check_uart(0,1)] and bluetooth_module_rename.ble.check_uart(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range bluetooth_module_rename.ble.check_uart(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port bluetooth_module_rename.ble.check_uart's trigger struct.
                bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bluetooth_module_rename_ble_self[dst_runtime]->_lf__check_uart;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range bluetooth_module_rename.ble.tx_string(0,1)->[bluetooth_module_rename.ble.tx_string(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of bluetooth_module_rename triggers 1 downstream reactions
            // through port bluetooth_module_rename.ble.tx_string.
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of bluetooth_module_rename, allocate an
            // array of trigger pointers for downstream reactions through port bluetooth_module_rename.ble.tx_string
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bluetooth_module_rename_main_self[src_runtime]->base.allocations); 
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range bluetooth_module_rename.disp.line1(0,1)->[bluetooth_module_rename.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of bluetooth_module_rename triggers 1 downstream reactions
            // through port bluetooth_module_rename.disp.line1.
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of bluetooth_module_rename, allocate an
            // array of trigger pointers for downstream reactions through port bluetooth_module_rename.disp.line1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bluetooth_module_rename_main_self[src_runtime]->base.allocations); 
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges bluetooth_module_rename.ble.tx_string(0,1)->[bluetooth_module_rename.ble.tx_string(0,1)] and bluetooth_module_rename.ble.tx_string(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range bluetooth_module_rename.ble.tx_string(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port bluetooth_module_rename.ble.tx_string's trigger struct.
                bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &bluetooth_module_rename_ble_self[dst_runtime]->_lf__tx_string;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges bluetooth_module_rename.disp.line1(0,1)->[bluetooth_module_rename.disp.line1(0,1)] and bluetooth_module_rename.disp.line1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range bluetooth_module_rename.disp.line1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port bluetooth_module_rename.disp.line1's trigger struct.
                bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &bluetooth_module_rename_disp_self[dst_runtime]->_lf__line1;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range bluetooth_module_rename.disp.line0(0,1)->[bluetooth_module_rename.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 3 of bluetooth_module_rename triggers 1 downstream reactions
            // through port bluetooth_module_rename.disp.line0.
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 3 of bluetooth_module_rename, allocate an
            // array of trigger pointers for downstream reactions through port bluetooth_module_rename.disp.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bluetooth_module_rename_main_self[src_runtime]->base.allocations); 
            bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges bluetooth_module_rename.disp.line0(0,1)->[bluetooth_module_rename.disp.line0(0,1)] and bluetooth_module_rename.disp.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range bluetooth_module_rename.disp.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port bluetooth_module_rename.disp.line0's trigger struct.
                bluetooth_module_rename_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &bluetooth_module_rename_disp_self[dst_runtime]->_lf__line0;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for bluetooth_module_rename.ble
    
    // For reference counting, set num_destinations for port bluetooth_module_rename.ble.rx_char.
    // Iterate over range bluetooth_module_rename.ble.rx_char(0,1)->[bluetooth_module_rename.ble.rx_char(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        bluetooth_module_rename_ble_self[src_runtime]->_lf_rx_char._base.num_destinations = 1;
        bluetooth_module_rename_ble_self[src_runtime]->_lf_rx_char._base.source_reactor = (self_base_t*)bluetooth_module_rename_ble_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range bluetooth_module_rename.ble.rx_char(0,1)->[bluetooth_module_rename.ble.rx_char(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of bluetooth_module_rename.ble triggers 1 downstream reactions
            // through port bluetooth_module_rename.ble.rx_char.
            bluetooth_module_rename_ble_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of bluetooth_module_rename.ble, allocate an
            // array of trigger pointers for downstream reactions through port bluetooth_module_rename.ble.rx_char
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &bluetooth_module_rename_ble_self[src_runtime]->base.allocations); 
            bluetooth_module_rename_ble_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges bluetooth_module_rename.ble.rx_char(0,1)->[bluetooth_module_rename.ble.rx_char(0,1)] and bluetooth_module_rename.ble.rx_char(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range bluetooth_module_rename.ble.rx_char(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port bluetooth_module_rename.ble.rx_char has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                bluetooth_module_rename_ble_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bluetooth_module_rename_main_self[dst_runtime]->_lf_ble.rx_char_trigger;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for bluetooth_module_rename.ble
    // **** Start non-nested deferred initialize for bluetooth_module_rename.disp
    
    
    
    
    // **** End of non-nested deferred initialize for bluetooth_module_rename.disp
    // **** End of non-nested deferred initialize for bluetooth_module_rename
    // Connect inputs and outputs for reactor bluetooth_module_rename.
    // Connect inputs and outputs for reactor bluetooth_module_rename.ble.
    // Connect bluetooth_module_rename.ble.check_uart(0,1)->[bluetooth_module_rename.ble.check_uart(0,1)] to port bluetooth_module_rename.ble.check_uart(0,1)
    // Iterate over ranges bluetooth_module_rename.ble.check_uart(0,1)->[bluetooth_module_rename.ble.check_uart(0,1)] and bluetooth_module_rename.ble.check_uart(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range bluetooth_module_rename.ble.check_uart(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bluetooth_module_rename_ble_self[dst_runtime]->_lf_check_uart = (_robotble_check_uart_t*)&bluetooth_module_rename_main_self[src_runtime]->_lf_ble.check_uart;
        }
    }
    // Connect bluetooth_module_rename.ble.tx_string(0,1)->[bluetooth_module_rename.ble.tx_string(0,1)] to port bluetooth_module_rename.ble.tx_string(0,1)
    // Iterate over ranges bluetooth_module_rename.ble.tx_string(0,1)->[bluetooth_module_rename.ble.tx_string(0,1)] and bluetooth_module_rename.ble.tx_string(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range bluetooth_module_rename.ble.tx_string(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bluetooth_module_rename_ble_self[dst_runtime]->_lf_tx_string = (_robotble_tx_string_t*)&bluetooth_module_rename_main_self[src_runtime]->_lf_ble.tx_string;
        }
    }
    // Connect bluetooth_module_rename.ble.rx_char(0,1)->[bluetooth_module_rename.ble.rx_char(0,1)] to port bluetooth_module_rename.ble.rx_char(0,1)
    // Iterate over ranges bluetooth_module_rename.ble.rx_char(0,1)->[bluetooth_module_rename.ble.rx_char(0,1)] and bluetooth_module_rename.ble.rx_char(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range bluetooth_module_rename.ble.rx_char(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bluetooth_module_rename_main_self[dst_runtime]->_lf_ble.rx_char = (_robotble_rx_char_t*)&bluetooth_module_rename_ble_self[src_runtime]->_lf_rx_char;
        }
    }
    // Connect inputs and outputs for reactor bluetooth_module_rename.disp.
    // Connect bluetooth_module_rename.disp.line0(0,1)->[bluetooth_module_rename.disp.line0(0,1)] to port bluetooth_module_rename.disp.line0(0,1)
    // Iterate over ranges bluetooth_module_rename.disp.line0(0,1)->[bluetooth_module_rename.disp.line0(0,1)] and bluetooth_module_rename.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range bluetooth_module_rename.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bluetooth_module_rename_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&bluetooth_module_rename_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect bluetooth_module_rename.disp.line1(0,1)->[bluetooth_module_rename.disp.line1(0,1)] to port bluetooth_module_rename.disp.line1(0,1)
    // Iterate over ranges bluetooth_module_rename.disp.line1(0,1)->[bluetooth_module_rename.disp.line1(0,1)] and bluetooth_module_rename.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range bluetooth_module_rename.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bluetooth_module_rename_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&bluetooth_module_rename_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    {
    }
    {
    }
    // Add port bluetooth_module_rename.ble.check_uart to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[bluetooth_module_rename_main].is_present_fields[0 + count] = &bluetooth_module_rename_main_self[0]->_lf_ble.check_uart.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[bluetooth_module_rename_main]._lf_intended_tag_fields[0 + count] = &bluetooth_module_rename_main_self[0]->_lf_ble.check_uart.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port bluetooth_module_rename.ble.tx_string to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[bluetooth_module_rename_main].is_present_fields[1 + count] = &bluetooth_module_rename_main_self[0]->_lf_ble.tx_string.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[bluetooth_module_rename_main]._lf_intended_tag_fields[1 + count] = &bluetooth_module_rename_main_self[0]->_lf_ble.tx_string.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port bluetooth_module_rename.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[bluetooth_module_rename_main].is_present_fields[2 + count] = &bluetooth_module_rename_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[bluetooth_module_rename_main]._lf_intended_tag_fields[2 + count] = &bluetooth_module_rename_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port bluetooth_module_rename.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[bluetooth_module_rename_main].is_present_fields[3 + count] = &bluetooth_module_rename_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[bluetooth_module_rename_main]._lf_intended_tag_fields[3 + count] = &bluetooth_module_rename_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port bluetooth_module_rename.ble.rx_char to array of is_present fields.
            envs[bluetooth_module_rename_main].is_present_fields[4 + count] = &bluetooth_module_rename_ble_self[0]->_lf_rx_char.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port bluetooth_module_rename.ble.rx_char to array of intended_tag fields.
            envs[bluetooth_module_rename_main]._lf_intended_tag_fields[4 + count] = &bluetooth_module_rename_ble_self[0]->_lf_rx_char.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance bluetooth_module_rename
    {
        bluetooth_module_rename_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bluetooth_module_rename_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        bluetooth_module_rename_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bluetooth_module_rename_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        bluetooth_module_rename_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bluetooth_module_rename_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        bluetooth_module_rename_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bluetooth_module_rename_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0003LL;
    
        // Set reaction priorities for ReactorInstance bluetooth_module_rename.ble
        {
            bluetooth_module_rename_ble_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            bluetooth_module_rename_ble_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
            bluetooth_module_rename_ble_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_2.index = 0xffffffffffff0003LL;
            bluetooth_module_rename_ble_self[0]->_lf__reaction_3.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bluetooth_module_rename_ble_self[0]->_lf__reaction_3.index = 0xffffffffffff0004LL;
        }
    
    
        // Set reaction priorities for ReactorInstance bluetooth_module_rename.disp
        {
            bluetooth_module_rename_disp_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bluetooth_module_rename_disp_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            bluetooth_module_rename_disp_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bluetooth_module_rename_disp_self[0]->_lf__reaction_1.index = 0xffffffffffff0004LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
